Error: java.lang.RuntimeException:
    org.apache.hadoop.hive.ql.metadata.HiveException:
    Hive Runtime Error while processing row
    {
        "bibnum" : 3112091,
        "title" :
            "\"A la Mala [videorecording] = Falling for Mala / Pantelion ;
            a Videocine, No Dancing Today, Eficine, Fidecine, Loreal Paris production ;
            Maybelline New York ; produced by Jorge Aragón, Fernando Pérez Gavilán M. ;
            written by Issa Lopez and Ari Rosen ; directed by Pitipol Ybarra.\"",
        "author" : "",
        "isbn" : "",
        "publicationyear" : "[2015]",
        "publisher" : "\"Lionsgate,\"",
        "subjects" :"\"Actresses Drama, Man woman relationships Drama, Romantic comedy films, Feature films, Fiction films, Motion pictures Spanish\"",
        "itemtype" : "acdvd",
        "itemcollection" : "nalndvd",
        "floatingitem" : "Floating",
        "itemlocation" : "hip",
        "reportdate" : "2017-09-01T00:00:00",
        "itemcount" : 1
    }
    at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:169)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:421)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by:
    org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row
    {
        "bibnum" : 3112091,
        "title" :
            "\"A la Mala [videorecording] = Falling for Mala / Pantelion ;
            a Videocine, No Dancing Today, Eficine, Fidecine, Loreal Paris production ;
            Maybelline New York ; produced by Jorge Aragón, Fernando Pérez Gavilán M. ;
            written by Issa Lopez and Ari Rosen ; directed by Pitipol Ybarra.\"",
        "author" : "",
        "isbn" : "",
        "publicationyear" : "[2015]",
        "publisher" : "\"Lionsgate,\"",
        "subjects" :"\"Actresses Drama, Man woman relationships Drama, Romantic comedy films, Feature films, Fiction films, Motion pictures Spanish\"",
        "itemtype" : "acdvd",
        "itemcollection" : "nalndvd",
        "floatingitem" : "Floating",
        "itemlocation" : "hip",
        "reportdate" : "2017-09-01T00:00:00",
        "itemcount" : 1
    }
    at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:499)
    at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:160) ... 8 more
Caused by:
    org.apache.hadoop.hive.ql.metadata.HiveException:
    org.apache.hadoop.ipc.RemoteException(java.io.IOException):
        File /user/hive/warehouse/library.db/bookspartitioned/.hive-staging_hive_2019-01-27_12-41-09_601_8214468303066055363-1/_task_tmp.-ext-10002/itemlocation=hip/_tmp.000000_0
        could only be replicated to 0 nodes instead of minReplication (=1). There are 2 datanode(s) running and no node(s) are excluded in this operation.
    at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1547)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3107)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3031)
    at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:724)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:492)
    at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
    at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:421)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
    at org.apache.hadoop.hive.ql.exec.FileSinkOperator.process(FileSinkOperator.java:790)
    at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:878)
    at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:95)
    at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:878)
    at org.apache.hadoop.hive.ql.exec.TableScanOperator.process(TableScanOperator.java:130)
    at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.forward(MapOperator.java:149)
    at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:489) ... 9 more
Caused by:
    org.apache.hadoop.ipc.RemoteException(java.io.IOException):
        File /user/hive/warehouse/library.db/bookspartitioned/.hive-staging_hive_2019-01-27_12-41-09_601_8214468303066055363-1/_task_tmp.-ext-10002/itemlocation=hip/_tmp.000000_0
        could only be replicated to 0 nodes instead of minReplication (=1). There are 2 datanode(s) running and no node(s) are excluded in this operation.
    at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1547)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3107)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3031)
    at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:724)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:492)
    at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
    at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:421)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
    at org.apache.hadoop.ipc.Client.call(Client.java:1475)
    at org.apache.hadoop.ipc.Client.call(Client.java:1412)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
    at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:418)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy13.addBlock(Unknown Source)
    at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1459)
    at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1255)
    at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:449)